services:
  - type: worker
    name: eliza-bulletproof
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python eliza_bulletproof.py
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: DevGruGold/xmrtnet
      - key: CHECK_INTERVAL
        value: "300"
    autoDeploy: true
    branch: main
