services:
  - type: worker
    name: eliza-truly-continuous
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python eliza_truly_continuous.py
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: DevGruGold/xmrtnet
      - key: CHECK_INTERVAL
        value: "300"
    autoDeploy: false
    branch: main
