services:
  # Python Autonomous Eliza Brain - Background Worker (NOT web service)
  - type: worker
    name: eliza-autonomous-brain
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python autonomous_eliza_continuous.py
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: DevGruGold/xmrtnet
      - key: GITHUB_EMAIL
        value: joeyleepcs@gmail.com
      - key: CHECK_INTERVAL
        value: "300"
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: true
    branch: main
    
  # Health monitoring cron job
  - type: cron
    name: eliza-health-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    schedule: "*/15 * * * *"  # Every 15 minutes
    startCommand: python eliza_health_check.py
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: DevGruGold/xmrtnet
